// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 John Coles - The Open CRM
// This file is part of The Open CRM, free software under the GNU AGPL v3.0 or
// later. See the LICENSE file at the repository root, or
// https://www.gnu.org/licenses/agpl-3.0.html. Distributed WITHOUT ANY WARRANTY.

// Branded purchase order PDF generation. Reuses the same brand palette as the
// quote PDF for visual consistency. Streams a binary PDF to the writable stream
// the caller provides (typically res).
//
// LIABILITY: The operator is responsible for verifying the accuracy of any PO
// generated by this service before sending it to a vendor. See LICENSE.

const PDFDocument = require('pdfkit');

const BRAND = {
  primary: '#2076CD',
  primaryDark: '#1B5FAD',
  accent: '#80CE99',
  accentDark: '#5DB97D',
  border: '#e5e7eb',
  textMuted: '#6b7280',
  text: '#111827',
  rowAlt: '#f9fafb',
};

function fmtMoney(n) {
  if (n === null || n === undefined || n === '') return '—';
  return `$${Number(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function fmtDate(d) {
  if (!d) return '—';
  const dt = typeof d === 'string' ? new Date(d) : d;
  return dt.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function header(doc, { deal, vendor, orgName }) {
  const top = doc.y;
  doc.fillColor(BRAND.primary).rect(0, top, doc.page.width, 6).fill();

  doc.fillColor(BRAND.text).font('Helvetica-Bold').fontSize(22).text(orgName || 'The Open CRM', 50, top + 22);
  doc.fillColor(BRAND.textMuted).font('Helvetica').fontSize(10).text('Purchase Order', 50, doc.y + 2);

  doc.font('Helvetica-Bold').fontSize(14).fillColor(BRAND.text)
    .text(`PO #${deal.po_number || deal.id}`, doc.page.width - 220, top + 22, { width: 170, align: 'right' });
  doc.font('Helvetica').fontSize(9).fillColor(BRAND.textMuted)
    .text(`Issued: ${fmtDate(new Date())}`, doc.page.width - 220, doc.y + 2, { width: 170, align: 'right' });
  if (deal.target_ship_date) {
    doc.text(`Target ship: ${fmtDate(deal.target_ship_date)}`, doc.page.width - 220, doc.y + 1, { width: 170, align: 'right' });
  }

  doc.y = top + 90;
  doc.fillColor(BRAND.border).rect(50, doc.y, doc.page.width - 100, 1).fill();
  doc.moveDown(1);
}

function vendorBlock(doc, { vendor }) {
  doc.fillColor(BRAND.textMuted).font('Helvetica-Bold').fontSize(8).text('VENDOR', 50);
  doc.fillColor(BRAND.text).font('Helvetica-Bold').fontSize(13).text(vendor?.name || 'Vendor', 50);
  doc.font('Helvetica').fontSize(10).fillColor(BRAND.text);
  if (vendor?.location) doc.text(vendor.location);
  if (vendor?.website)  doc.text(vendor.website);
  if (vendor?.phone)    doc.text(vendor.phone);
  doc.moveDown(0.7);
}

function shipBlock(doc, { deal }) {
  if (!deal.ship_to && !deal.poc_name) return;
  doc.fillColor(BRAND.textMuted).font('Helvetica-Bold').fontSize(8).text('SHIP TO');
  doc.fillColor(BRAND.text).font('Helvetica').fontSize(10);
  if (deal.ship_to) doc.text(deal.ship_to);
  const pocLine = [deal.poc_name, deal.poc_phone, deal.poc_email].filter(Boolean).join(' · ');
  if (pocLine) doc.text(pocLine);
  doc.moveDown(0.7);
}

function lineItemsTable(doc, { items, totalAmount, vendorAmount }) {
  const startX = 50;
  const usableWidth = doc.page.width - 100;
  const cols = [
    { key: 'description', label: 'Description', width: usableWidth * 0.58, align: 'left' },
    { key: 'qty',         label: 'Qty',         width: usableWidth * 0.10, align: 'right' },
    { key: 'unit',        label: 'Unit Cost',   width: usableWidth * 0.16, align: 'right' },
    { key: 'total',       label: 'Total',       width: usableWidth * 0.16, align: 'right' },
  ];

  let x = startX;
  doc.fillColor(BRAND.primaryDark).rect(startX, doc.y, usableWidth, 22).fill();
  doc.fillColor('white').font('Helvetica-Bold').fontSize(9);
  for (const col of cols) {
    doc.text(col.label, x + 6, doc.y + 7, { width: col.width - 12, align: col.align });
    x += col.width;
  }
  doc.y += 22;

  doc.font('Helvetica').fontSize(10).fillColor(BRAND.text);
  let alt = false;
  let runningTotal = 0;
  for (const li of items || []) {
    const total = Number(li.quantity || 1) * Number(li.unit_price || 0);
    runningTotal += total;
    const rowHeight = Math.max(20, doc.heightOfString(li.description || '', { width: cols[0].width - 12 }) + 8);
    if (alt) doc.fillColor(BRAND.rowAlt).rect(startX, doc.y, usableWidth, rowHeight).fill();
    alt = !alt;

    x = startX;
    const top = doc.y + 5;
    doc.fillColor(BRAND.text);
    doc.text(li.description || '', x + 6, top, { width: cols[0].width - 12 });
    x += cols[0].width;
    doc.text(String(li.quantity || 1), x + 6, top, { width: cols[1].width - 12, align: 'right' });
    x += cols[1].width;
    doc.text(fmtMoney(li.unit_price), x + 6, top, { width: cols[2].width - 12, align: 'right' });
    x += cols[2].width;
    doc.font('Helvetica-Bold').text(fmtMoney(total), x + 6, top, { width: cols[3].width - 12, align: 'right' });
    doc.font('Helvetica');
    doc.y = top + rowHeight - 5;
    if (doc.y > doc.page.height - 130) doc.addPage();
  }

  doc.fillColor(BRAND.border).rect(startX, doc.y, usableWidth, 1).fill();
  doc.y += 8;

  const finalTotal = runningTotal || vendorAmount || totalAmount || 0;
  doc.fillColor(BRAND.text).font('Helvetica-Bold').fontSize(13);
  doc.text('Total', startX, doc.y, { width: usableWidth - 12 - cols[3].width / 2, align: 'right' });
  doc.fillColor(BRAND.primary).fontSize(15);
  doc.text(fmtMoney(finalTotal), startX, doc.y - 18, { width: usableWidth - 12, align: 'right' });
  doc.fillColor(BRAND.text).fontSize(10);
  doc.moveDown(2);
}

function termsBlock(doc) {
  doc.fillColor(BRAND.textMuted).font('Helvetica-Bold').fontSize(8).text('TERMS', 50);
  const terms = [
    'Acknowledge receipt of this PO within 2 business days.',
    'Notify us in writing of any change to lead time, pricing, or scope before fulfilling.',
    'All deliverables to be shipped per the ship-to information above.',
    'Submit invoice referencing this PO number to accounting on shipment.',
  ];
  doc.fillColor(BRAND.text).font('Helvetica').fontSize(8.5);
  for (const t of terms) {
    doc.text(`• ${t}`, 50, doc.y + 2, { width: doc.page.width - 100 });
  }
  doc.moveDown(1);
}

function footer(doc, { orgName }) {
  const y = doc.page.height - 60;
  doc.fillColor(BRAND.border).rect(50, y, doc.page.width - 100, 1).fill();
  doc.fillColor(BRAND.textMuted).font('Helvetica').fontSize(7)
    .text(
      'This purchase order is generated from data entered by the issuing organization. The software author makes no warranty as to its accuracy or completeness; recipients should independently verify pricing, lead times, and specifications before acting upon them.',
      50, y + 6,
      { width: doc.page.width - 100, align: 'center' }
    );
  doc.fillColor(BRAND.textMuted).font('Helvetica').fontSize(8)
    .text(`${orgName || 'The Open CRM'} · Generated by The Open CRM`, 50, y + 30, {
      width: doc.page.width - 100, align: 'center',
    });
}

/**
 * Render a PO PDF to the given writable stream.
 */
function renderPurchaseOrderPdf({ deal, vendor, orgName, lineItems, vendorAmount }, stream) {
  const doc = new PDFDocument({ size: 'LETTER', margin: 50, bufferPages: true });
  doc.pipe(stream);

  header(doc, { deal, vendor, orgName });
  vendorBlock(doc, { vendor });
  shipBlock(doc, { deal });

  // If no line items provided, synthesize a single line from the deal title + vendor amount.
  const items = (lineItems && lineItems.length > 0) ? lineItems : [{
    description: deal.title || 'See attached scope',
    quantity: 1,
    unit_price: vendorAmount ?? deal.amount ?? null,
  }];

  lineItemsTable(doc, { items, totalAmount: deal.amount, vendorAmount });
  termsBlock(doc);

  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    footer(doc, { orgName });
  }

  doc.end();
}

module.exports = { renderPurchaseOrderPdf };
